"""Table of which questions are escalated, by question structure (generated from results/e9/<tag>/escalated.json).

Why: the paragraph "Which questions are
escalated" quoted a few groups; the table gives every structure of the three datasets on both backbones at the
main-table operating point (scripts/e9_escalated.py: E9_SRC maps, E9_MODE, B_IRCoT/2).
Cells: share of the group escalated to IRCoT + to Search-o1 (%), and the net change in EM of the group (EM points;
gained minus lost questions, averaged over Search-o1 seeds), tinted by the change itself.
Output: paper/tables/table_escalated.tex (a tabular; caption and float live in the section file)
Usage:  python3 scripts/make_table_escalated.py      standard library only
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TAGS = [("llama31-8b", "Llama-3.1-8B"), ("qwen3-8b", "Qwen3-8B")]
GROUPS = [("hotpotqa", "HotpotQA", [("bridge", "bridge"), ("comparison", "comparison")]),
          ("2wikimultihopqa", "2WikiMultiHopQA", [("compositional", "compositional"), ("comparison", "comparison"),
                                                   ("inference", "inference"), ("bridge_comparison", "bridge-comparison")]),
          ("musique", "MuSiQue", [("2 hops", "2 hops"), ("3 hops", "3 hops"), ("4 hops", "4 hops")])]


def main():
    data = {t: json.loads((ROOT / "results" / "e9" / t / "escalated.json").read_text()) for t, _ in TAGS}
    lines = ["% Generated by scripts/make_table_escalated.py from results/e9/<tag>/escalated.json. Do not edit by hand.",
             r"\begin{tabular}{@{}lrcccc@{\hspace{\tabcolsep}}}", r"\toprule",
             r" & & \multicolumn{2}{c}{" + TAGS[0][1] + r"} & \multicolumn{2}{c}{" + TAGS[1][1] + r"} \\",
             r"\cmidrule(lr){3-4}\cmidrule(lr){5-6}",
             r"Structure & $n$ & Esc.\ (\%) & $\Delta$EM & Esc.\ (\%) & $\Delta$EM \\", r"\midrule"]
    for g, (ds, name, rows) in enumerate(GROUPS):
        if g:
            lines.append(r"\cmidrule(lr){1-6}")
        lines.append(r"\grp{6}{" + name + r"} \\")
        for key, label in rows:
            cells, n = [], None
            for t, _ in TAGS:
                r = data[t][ds][key]
                n = r["n"]
                esc = f"{100 * r['ircot'] / n:.0f}\\,+\\,{100 * r['searcho1'] / n:.0f}"
                d = 100 * (r["gain"] - r["loss"]) / n
                cells += [esc, rf"\hct{{{d:.1f}}}{{0}}{{{d:+.1f}}}"]
            lines.append(r"\base " + label + f" & {n} & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    out = ROOT / "results" / "tables" / "table_escalated.tex"
    out.write_text("\n".join(lines))
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
