"""Table of escalation under three calibration sets (generated from results/e9/<tag>/priced_{traincal,,dev1000}.json).

Why: the escalation maps need
in-distribution calibration questions; the text stated it with two numbers, the table shows the main-table operating point
(E9_MODE, B_IRCoT/2) when the maps are fitted on the 500 training calibration questions, on 500 development questions with
one Search-o1 seed, and on the 1,000 development questions with three seeds used in the paper (E9_SRC).
Cells: EM, tinted against the paper's maps of the same backbone, and the share of questions escalated (%).
Output: paper/tables/table_calsrc.tex (a tabular; caption and float live in the section file)
Usage:  python3 scripts/make_table_calsrc.py      standard library only
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from make_table1 import E9_MODE, E9_SRC  # noqa: E402

TAGS = [("llama31-8b", "Llama-3.1-8B-Instruct"), ("qwen3-8b", "Qwen3-8B")]
DATASETS = [("hotpotqa", "HotpotQA"), ("2wikimultihopqa", "2Wiki"), ("musique", "MuSiQue")]
SOURCES = [("priced_traincal", "training, 500"), ("priced", "development, 500, 1 seed"),
           (E9_SRC, "development, 1{,}000, 3 seeds")]


def point(tag, src, ds):
    d = json.loads((ROOT / "results" / "e9" / tag / f"{src}.json").read_text())[ds]
    return d["points"][f"plan/{E9_MODE}/B_IRCoT/2"]


def main():
    ncol = 1 + len(DATASETS)
    lines = ["% Generated by scripts/make_table_calsrc.py from results/e9/<tag>/priced*.json. Do not edit by hand.",
             r"\begin{tabular}{@{}l" + "c" * len(DATASETS) + r"@{\hspace{\tabcolsep}}}", r"\toprule",
             r"Calibration questions & " + " & ".join(n for _, n in DATASETS) + r" \\", r"\midrule"]
    for t, (tag, name) in enumerate(TAGS):
        if t:
            lines.append(r"\midrule")
        lines.append(rf"\grp{{{ncol}}}{{{name}}} \\")
        ref = {ds: point(tag, E9_SRC, ds)["em"] for ds, _ in DATASETS}
        for src, label in SOURCES:
            cells = []
            for ds, _ in DATASETS:
                p = point(tag, src, ds)
                share = 100 * sum(p["share"].values())
                cells.append(rf"\hcs{{{p['em']:.1f}}}{{{ref[ds]:.1f}}}\,\textcolor{{black!55}}{{\scriptsize({share:.0f})}}")
            mark = r"\ours " if src == E9_SRC else r"\base "
            lines.append(mark + label + " & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    out = ROOT / "results" / "tables" / "table_calsrc.tex"
    out.write_text("\n".join(lines))
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
