"""Case-study table: one test question traced through the method (plan, step estimates, reliability, escalation).

Why: a reader sees what the reliability
check reads and what it decides on one real question. Everything in the table comes from stored outputs: the plan and the
default step answers (results/e3/<tag>/test/<ds>/questions.jsonl), the step error estimates and propagation weights of
the fitted quality model (results/e3/<tag>/models/<ds>_logreg.pkl, as in scripts/e9_escalate.py), the automatic step
labels, the escalation choice of the main-table row (results/e9/<tag>/<E9_SRC>.json, E9_MODE, B_IRCoT/2) and the
alternative's answer (results/e2/<tag>/test/<ds>/).
--list prints the candidate questions (escalated, plan wrong, alternative right on every seed, at least one step labelled
wrong); the example is then picked by hand among them and named with --qid.
Output: paper/tables/table_case.tex (a tabular; caption and float live in the section file)
Usage:  python scripts/make_table_case.py --tag qwen3-8b --ds musique --list
        python scripts/make_table_case.py --tag qwen3-8b --ds musique --qid <qid>      (project venv: unpickles the model)
"""
import argparse
import json
import pickle
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))
from make_table1 import E9_MODE, E9_SRC  # noqa: E402

SEEDS = (17, 29, 43)
ALT_NAME = {"ircot": "IRCoT", "searcho1": "Search-o1"}
BACKBONES = {"llama31-8b": "Llama-3.1-8B-Instruct", "qwen3-8b": "Qwen3-8B"}
DSNAME = {"hotpotqa": "HotpotQA", "2wikimultihopqa": "2WikiMultiHopQA", "musique": "MuSiQue"}


def rd(p):
    return [json.loads(line) for line in open(p)]


def tex(s):
    s = str(s)
    for a, b in (("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("$", r"\$"), ("#", r"\#"), ("_", r"\_"),
                 ("{", r"\{"), ("}", r"\}"), ("~", r"\textasciitilde{}"), ("^", r"\textasciicircum{}")):
        s = s.replace(a, b)
    return s


def load(tag, ds):
    e3, e2 = ROOT / "results" / "e3" / tag, ROOT / "results" / "e2" / tag / "test" / ds
    qm = pickle.load(open(e3 / "models" / f"{ds}_logreg.pkl", "rb"))
    qs = {q["qid"]: q for q in rd(e3 / "test" / ds / "questions.jsonl")}
    pt = json.loads((ROOT / "results" / "e9" / tag / f"{E9_SRC}.json").read_text())[ds]["points"]
    choice = pt[f"plan/{E9_MODE}/B_IRCoT/2"]["choice"]
    alts = {"ircot": {s: {r["qid"]: r for r in rd(next(e2.glob("ircot_k*.jsonl")))} for s in SEEDS},
            "searcho1": {s: {r["qid"]: r for r in rd(e2 / f"searcho1_s{s}.jsonl")} for s in SEEDS}}
    return qm, qs, choice, alts


def trace(qm, q):
    steps = q["steps"]
    eps = qm.eps([s["feat"] for s in steps])
    pis = qm.pis([{"id": s["id"], "deps": s["deps"], "kind": s["kind"]} for s in steps])
    rel = 1.0
    rows = []
    for s, e in zip(steps, eps):
        p = pis.get(s["id"], 1.0)
        rel *= 1 - e * p
        rows.append((s, float(e), float(p)))
    return rows, rel


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--tag", required=True)
    ap.add_argument("--ds", required=True)
    ap.add_argument("--qid")
    ap.add_argument("--list", action="store_true")
    args = ap.parse_args()
    qm, qs, choice, alts = load(args.tag, args.ds)
    if args.list:
        for qid, alt in sorted(choice.items()):
            q = qs.get(qid)
            if alt not in alts or q is None or q["base"]["em"] > 0:
                continue
            if min(alts[alt][s][qid]["em"] for s in SEEDS) < 1 or not any(s.get("label") == "error" for s in q["steps"]):
                continue
            rows, rel = trace(qm, q)
            print(f"{qid}  {alt}  s={rel:.2f}  {q['question']}")
            for s, e, p in rows:
                print(f"    #{s['id']} {s['kind']} eps={e:.2f} pi={p:.2f} [{s.get('label')}] {s['q']} -> {s['a0']}")
            print(f"    plan: {q['base']['pred']}   {ALT_NAME[alt]}: {alts[alt][17][qid]['pred']}   gold: {q['answers']}")
        return
    q = qs[args.qid]
    alt = choice[args.qid]
    rows, rel = trace(qm, q)
    lab = {"correct": "right", "error": "wrong", "undet": "undecidable"}
    lines = ["% Generated by scripts/make_table_case.py from results/e3, results/e9 and results/e2. Do not edit by hand.",
             r"\begin{tabular}{@{}l>{\raggedright\arraybackslash}p{0.62\linewidth}cc@{}}", r"\toprule",
             r"\multicolumn{4}{@{}>{\raggedright\arraybackslash}p{0.97\linewidth}@{}}{\textbf{Question} (" + DSNAME[args.ds]
             + ", " + BACKBONES[args.tag] + "): " + tex(q["question"]) + r"} \\",
             r"\multicolumn{4}{@{}l@{}}{\textbf{Gold answer}: " + tex(" / ".join(q["answers"])) + r"} \\", r"\midrule",
             r"Step & Sub-question $\to$ default answer & $\hat\varepsilon_v$ & Label \\", r"\midrule"]
    for s, e, p in rows:
        lines.append(rf"\#{s['id']} {s['kind']} & {tex(s['q'])} $\to$ \emph{{{tex(s['a0'])}}} & {e:.2f} & "
                     + lab.get(s.get("label"), r"--") + r" \\")
    alt_pred = alts[alt][17][args.qid]["pred"]
    lines += [r"\midrule",
              r"\multicolumn{4}{@{}>{\raggedright\arraybackslash}p{0.97\linewidth}@{}}{Reliability $\hat s=" + f"{rel:.2f}"
              + r"$; plan answer \emph{" + tex(q["base"]["pred"]) + r"} (wrong). Escalated to " + ALT_NAME[alt]
              + r", which answers \emph{" + tex(alt_pred) + r"} (right).} \\",
              r"\bottomrule", r"\end{tabular}", ""]
    out = ROOT / "results" / "tables" / "table_case.tex"
    out.write_text("\n".join(lines))
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
