"""Appendix tables of the paper, generated from the e2 / e3 summaries; never edit the .tex by hand.

tableA_ircot.tex   IRCoT at the three reduced budgets and with its official setting, and CoVe, next to the method at B_SC:
                   EM, F1, tokens per question (thousands, with a bar as in the main table's cost column) and calls; one
                   block per backbone, datasets as column groups (the main table uses the budget closest to ours). EM and
                   F1 are tinted against the method's row of the same dataset (\\hc; one tint reference per table, user
                   2026-10-07 evening), best bold and second underlined per block and column.
tableA_boot.tex    Paired bootstrap of the method at B_SC against each baseline: EM difference and 95% interval
                   (10,000 resamples over questions, scripts/e3_bootstrap.py), per backbone and dataset; CoVe's own EM is
                   in tableA_ircot's companion rows below. Each cell is tinted by the difference itself (reference 0, \\hct)
                   and bold when the interval excludes zero.
Input:  results/e2/<tag>/test/summary.json, results/e3/<tag>/test/{summary,bootstrap}.json
Output: paper/tables/tableA_ircot.tex, paper/tables/tableA_boot.tex
Usage:  python3 scripts/make_tables_app.py [--tags llama31-8b qwen3-8b]      standard library only
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATASETS = [("hotpotqa", "HotpotQA"), ("2wikimultihopqa", "2WikiMultiHopQA"), ("musique", "MuSiQue")]
BACKBONES = {"llama31-8b": "Llama-3.1-8B-Instruct", "qwen3-8b": "Qwen3-8B"}
HEADER = "% Generated by scripts/make_tables_app.py from results/e2 and results/e3 summaries. Do not edit by hand.\n"
BOOT = [("rag", "Standard RAG"), ("sc5", "Self-Consistency"), ("selfask", "Self-Ask"), ("ircot", "IRCoT (official)"),
        ("searcho1", "Search-o1"), ("pyrag", "PyRAG"), ("planbudget", "Plan-and-Budget"), ("cove", "Chain-of-Verification")]


def load(*parts):
    p = ROOT.joinpath("results", *parts)
    return json.loads(p.read_text()) if p.exists() else {}


def marks(values):
    """{row: '[\\textbf]' | '[\\underline]' | ''}: best / second best of a column (one decimal; ties share the mark)."""
    vals = sorted({round(v, 1) for v in values.values()}, reverse=True)
    return {r: r"[\textbf]" if round(v, 1) == vals[0] else r"[\underline]" if len(vals) > 1 and round(v, 1) == vals[1]
            else "" for r, v in values.items()}


def ircot_table(tags):
    """Datasets as column groups and configurations as rows (one block per backbone, as in the main table), so that
    the table stays a third of the page high with both backbones."""
    lines = [HEADER + r"\begin{tabular}{@{}l" + "rrrr" * len(DATASETS) + "@{}}", r"\toprule",
             " & " + " & ".join(rf"\multicolumn{{4}}{{c}}{{{name}}}" for _, name in DATASETS) + r" \\",
             "".join(rf"\cmidrule(lr){{{2 + 4 * i}-{5 + 4 * i}}}" for i in range(len(DATASETS))),
             "Configuration & " + " & ".join(r"EM & F1 & Tok.\,(k) & Calls" for _ in DATASETS) + r" \\", r"\midrule"]
    for tag in tags:
        e2 = load("e2", tag, "test", "summary.json").get("summary", {})
        e3 = load("e3", tag, "test", "summary.json")
        if not e2:
            continue
        if lines[-1] != r"\midrule":
            lines.append(r"\midrule")   # a rule between backbone blocks, as in the main table
        lines.append(r"\grp{%d}{%s} \\" % (1 + 4 * len(DATASETS), BACKBONES[tag]))
        tokmax = max(v["tok"] / 1000 for ds, _ in DATASETS for k, v in e2.get(ds, {}).items()
                     if k.startswith("ircot") or k == "cove")
        # reduced budgets ircotb_d<demos>_p<cap>_k<K>: one row per (demos, cap); K, the paragraphs per retrieval, is the
        # dataset's tuned value (Appendix C), so the same row may carry different keys per dataset
        cfg = lambda k: tuple(int(x[1:]) for x in k.split("_")[1:3])
        configs = sorted({cfg(k) for ds, _ in DATASETS for k in e2.get(ds, {}) if k.startswith("ircotb_")})
        rows = []   # (label, is_ours, {ds: {em, f1, tok, calls}})
        for n_demo, cap in configs:
            vals = {ds: v for ds, _ in DATASETS for k, v in e2.get(ds, {}).items()
                    if k.startswith("ircotb_") and cfg(k) == (n_demo, cap)}
            rows.append((f"{n_demo} demo{'s' if n_demo != 1 else ''}, $\\le${cap} paragraphs", False, vals))
        for k, label in (("ircot", "official setting"), ("cove", "CoVe (reference)")):
            rows.append((label, False, {ds: e2[ds][k] for ds, _ in DATASETS if k in e2.get(ds, {})}))
        ours = {ds: e3[ds]["main"]["B_SC"] for ds, _ in DATASETS if "B_SC" in e3.get(ds, {}).get("main", {})}
        rows.append((r"\method{} ($B_{\mathrm{SC}}$)", True,
                     {ds: {"em": v["em"], "f1": v["f1"], "tok": v["total_tok"]} for ds, v in ours.items()}))
        mk = {(ds, m): marks({i: r[2][ds][m] for i, r in enumerate(rows) if ds in r[2]}) for ds, _ in DATASETS
              for m in ("em", "f1")}
        for i, (label, is_ours, vals) in enumerate(rows):
            cells = []
            for ds, _ in DATASETS:
                v = vals.get(ds)
                if v is None:
                    cells += [r"\tbd"] * 4
                    continue
                for m in ("em", "f1"):
                    fmt = mk[ds, m].get(i, "")
                    cells.append(rf"\hc{fmt}{{{v[m]:.1f}}}{{{ours[ds][m]:.1f}}}" if ds in ours else f"{v[m]:.1f}")
                cells.append(rf"\cbar{{{v['tok'] / 1000:.1f}}}{{{tokmax:.1f}}}")
                cells.append(f"{v['calls']:.1f}" if "calls" in v else r"\na")
            lines.append((r"\ours " if is_ours else r"\base ") + label + " & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(lines)


def boot_table(tags):
    lines = [HEADER + r"\begin{tabular}{@{}l" + "c" * len(DATASETS) + "@{}}", r"\toprule",
             "Baseline & " + " & ".join(name for _, name in DATASETS) + r" \\", r"\midrule"]
    for tag in tags:
        b = load("e3", tag, "test", "bootstrap.json")
        if not b:
            continue
        if lines[-1] != r"\midrule":
            lines.append(r"\midrule")   # a rule between backbone blocks, as in the main table
        lines.append(r"\grp{%d}{%s} \\" % (1 + len(DATASETS), BACKBONES[tag]))
        for key, name in BOOT:
            cells = []
            for ds, _ in DATASETS:
                x = b.get(ds, {}).get("B_SC", {}).get(key)
                if not x:
                    cells.append(r"\tbd")
                    continue
                sig = x["lo"] > 0 or x["hi"] < 0
                cell = f"{x['diff']:+.1f} [{x['lo']:+.1f}, {x['hi']:+.1f}]"
                bold = "[\\textbf]" if sig else ""   # a plain variable: '\t' inside an f-string expression would be a TAB
                cells.append(rf"\hct{bold}{{{x['diff']:.2f}}}{{0}}{{{cell}}}")
            lines.append(name + " & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--tags", nargs="+", default=list(BACKBONES))
    args = ap.parse_args()
    out = ROOT / "results" / "tables"
    (out / "tableA_ircot.tex").write_text(ircot_table(args.tags))
    (out / "tableA_boot.tex").write_text(boot_table(args.tags))
    print("wrote paper/tables/tableA_ircot.tex, paper/tables/tableA_boot.tex")


if __name__ == "__main__":
    main()
