"""Tables of the allocation comparisons and of the quality-model diagnostics, generated from the e3 summaries; never edit
the .tex by hand. Both follow the main table's style: one block per backbone under a \\grp header row, the method's row marked with \\ours, best bold and second
underlined, and cells tinted by their change against a stated reference (\\hc; the key, \\tintlegend, sits under the table in
the section file).

Allocation table: per dataset EM at verification budget B_SC and B_SC/2 (linear interpolation between neighbouring
operating points, scripts/e3_summarize.py) and AUC-QC (area under the EM-verification-token curve up to Verify-All's cost,
normalised by that cost). Tint: change against the method's own row of the same backbone, on the fine scale (\\hcs, key \\tintlegendfine: the rows differ by
a point or two). The oracle row is an upper bound, printed in grey without tint or marks.
Diagnostics table (one column wide): AUROC and ECE (x100) of the step error estimate on the labelled test steps for the
type prior, the method's logistic regression (row "\\method{}") and boosted trees (results/e3/<tag>/test/diag_estimators.json,
from scripts/e3_diag_estimators.py); tint: change against the type prior (\\hc for AUROC, \\hcl for ECE, lower is better).
To fit one column the headers carry no arrows and the row label no "(logistic)"; the caption gives both.
Input:  results/e3/<tag>/test/summary.json, results/e3/<tag>/test/diag_estimators.json
Output: paper/tables/table_alloc.tex, table_alloc_small.tex (one column, EM at B_SC; the EDBT build), table_diag.tex
        (tabulars; captions live in the section file)
Usage:  python3 scripts/make_tables23.py [--tags llama31-8b qwen3-8b]      standard library only
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATASETS = [("hotpotqa", "HotpotQA"), ("2wikimultihopqa", "2WikiMultiHopQA"), ("musique", "MuSiQue")]
BACKBONES = {"llama31-8b": "Llama-3.1-8B-Instruct", "qwen3-8b": "Qwen3-8B"}
ROWS = [("plan_only", "Plan-Only (no verification)"), ("verify_all", "Verify-All"), ("type_static", "Type-Static"),
        ("question_level", "Question-Level"), ("full", r"\method{} w/o escalation"), ("no_prop", r"\quad w/o propagation"),
        ("prior_eps", r"\quad w/o instance estimates"), ("no_probe", r"\quad w/o probing"),
        ("gbdt", r"\quad boosted-tree estimator"), ("oracle", "Oracle, single step (upper bound)")]
COLS = [("EM@B_SC", r"$B_{\mathrm{SC}}$"), ("EM@B_SC/2", r"$B_{\mathrm{SC}}/2$"), ("AUC-QC", "AUC")]
HEADER = "% Generated by scripts/make_tables23.py from results/e3/<tag>/test/summary.json. Do not edit by hand.\n"


def load(tag):
    p = ROOT / "results" / "e3" / tag / "test" / "summary.json"
    return json.loads(p.read_text()) if p.exists() else {}


def marks(values):
    """{row: '[\\textbf]' | '[\\underline]' | ''} for best / second best (rounded to one decimal, ties share the mark)."""
    vals = sorted({round(v, 1) for v in values.values()}, reverse=True)
    out = {}
    for r, v in values.items():
        v = round(v, 1)
        out[r] = r"[\textbf]" if v == vals[0] else (r"[\underline]" if len(vals) > 1 and v == vals[1] else "")
    return out


def alloc_block(tag):
    s = load(tag)
    ncol = 1 + 3 * len(DATASETS)
    lines = [rf"\grp{{{ncol}}}{{{BACKBONES[tag]}}} \\"]
    if not s:
        lines.append(r"\multicolumn{" + str(ncol) + r"}{l}{\base\textcolor{black!50}{\emph{running}}} \\")
        return lines
    cells = {}
    for ds, _ in DATASETS:
        t2 = s.get(ds, {}).get("table2", {})
        for c, _ in COLS:
            ref = t2.get("full", {}).get(c)
            col = {r: t2[r][c] for r, _ in ROWS if r in t2 and r != "oracle" and t2[r].get(c) is not None}
            mk = marks(col)
            for r, _ in ROWS:
                v = t2.get(r, {}).get(c)
                if v is None:
                    cells[r, ds, c] = r"\tbd"
                elif r == "plan_only" and c == "AUC-QC" or ref is None:
                    cells[r, ds, c] = r"\na"
                elif r == "oracle":
                    cells[r, ds, c] = rf"\textcolor{{black!55}}{{{v:.1f}}}"
                else:
                    cells[r, ds, c] = rf"\hcs{mk.get(r, '')}{{{v:.1f}}}{{{ref:.1f}}}"   # fine tint scale (+-5)
    for r, name in ROWS:
        if r in ("full", "oracle"):
            lines.append(r"\cmidrule(lr){1-" + str(ncol) + "}")
        lead = r"\ours " if r == "full" else r"\base "
        if r == "oracle":
            name = rf"\textcolor{{black!55}}{{{name}}}"
        lines.append(lead + name + " & " + " & ".join(cells[r, ds, c] for ds, _ in DATASETS for c, _ in COLS) + r" \\")
    return lines


def table_alloc(tags):
    lines = [HEADER + r"\begin{tabular}{@{}l" + "ccc" * len(DATASETS) + r"@{\hspace{\tabcolsep}}}", r"\toprule",
             " & " + " & ".join(rf"\multicolumn{{3}}{{c}}{{{name}}}" for _, name in DATASETS) + r" \\",
             "".join(rf"\cmidrule(lr){{{2 + 3 * i}-{4 + 3 * i}}}" for i in range(len(DATASETS))),
             r"Variant (EM at budget) & " + " & ".join(h for _ in DATASETS for _, h in COLS) + r" \\", r"\midrule"]
    for i, tag in enumerate(tags):
        if i:
            lines.append(r"\midrule")
        lines += alloc_block(tag)
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(lines)


# One-column version for the EDBT build: EM at B_SC only, without the probing and boosted-tree rows (they change EM by at most 0.5; stated in the text).
SMALL_ROWS = [("plan_only", "Plan-Only"), ("verify_all", "Verify-All"), ("type_static", "Type-Static"),
              ("question_level", "Question-Level"), ("full", r"\method{} w/o escalation"), ("no_prop", r"\quad w/o propagation"),
              ("prior_eps", r"\quad w/o instance est."), ("oracle", "Oracle (one step)")]


def table_alloc_small(tags):
    ncol = 1 + len(DATASETS)
    lines = [HEADER + r"\begin{tabular}{@{}l" + "c" * len(DATASETS) + r"@{\hspace{\tabcolsep}}}", r"\toprule",
             r"Allocation (EM at $B_{\mathrm{SC}}$) & " + " & ".join(name.replace("WikiMultiHopQA", "Wiki") for _, name in DATASETS)
             + r" \\", r"\midrule"]
    for i, tag in enumerate(tags):
        if i:
            lines.append(r"\midrule")
        lines.append(rf"\grp{{{ncol}}}{{{BACKBONES[tag]}}} \\")
        t2 = {ds: load(tag).get(ds, {}).get("table2", {}) for ds, _ in DATASETS}
        mk = {ds: marks({r: t2[ds][r]["EM@B_SC"] for r, _ in SMALL_ROWS if r != "oracle" and t2[ds].get(r, {}).get("EM@B_SC") is not None})
              for ds, _ in DATASETS}
        for r, name in SMALL_ROWS:
            if r in ("full", "oracle"):
                lines.append(r"\cmidrule(lr){1-" + str(ncol) + "}")
            cells = []
            for ds, _ in DATASETS:
                v, ref = t2[ds].get(r, {}).get("EM@B_SC"), t2[ds].get("full", {}).get("EM@B_SC")
                if v is None:
                    cells.append(r"\tbd")
                elif r == "oracle":
                    cells.append(rf"\textcolor{{black!55}}{{{v:.1f}}}")
                else:
                    cells.append(rf"\hcs{mk[ds].get(r, '')}{{{v:.1f}}}{{{ref:.1f}}}")
            label = rf"\textcolor{{black!55}}{{{name}}}" if r == "oracle" else name
            lines.append((r"\ours " if r == "full" else r"\base ") + label + " & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(lines)


DIAG_ROWS = [("prior", r"Type prior"), ("logreg", r"\method{}"), ("gbdt", r"Boosted trees")]


def load_diag(tag):
    p = ROOT / "results" / "e3" / tag / "test" / "diag_estimators.json"
    return json.loads(p.read_text()) if p.exists() else {}


def table_diag(tags):
    lines = [HEADER.replace("summary.json", "diag_estimators.json") + r"\begin{tabular}{@{}l" + "cc" * len(DATASETS) + r"@{\hspace{\tabcolsep}}}",
             r"\toprule",
             " & " + " & ".join(rf"\multicolumn{{2}}{{c}}{{{name}}}" for _, name in DATASETS) + r" \\",
             "".join(rf"\cmidrule(lr){{{2 + 2 * i}-{3 + 2 * i}}}" for i in range(len(DATASETS))),
             r"Estimator & " + " & ".join(r"AUROC & ECE" for _ in DATASETS) + r" \\", r"\midrule"]
    for i, tag in enumerate(tags):
        if i:
            lines.append(r"\midrule")
        lines.append(rf"\grp{{{1 + 2 * len(DATASETS)}}}{{{BACKBONES[tag]}}} \\")
        d = load_diag(tag)
        cells = {}
        for ds, _ in DATASETS:
            e = d.get(ds, {})
            for m, sign in (("auroc", 1), ("ece", -1)):
                vals = {k: 100 * e[k][m] for k, _ in DIAG_ROWS if k in e}
                mk = marks({k: sign * v for k, v in vals.items()})
                for k, _ in DIAG_ROWS:
                    if k not in vals:
                        cells[k, ds, m] = r"\tbd"
                    elif k == "prior":
                        cells[k, ds, m] = (mk[k][1:-1] + "{" if mk[k] else "{") + f"{vals[k]:.1f}" + "}"
                    else:
                        macro = r"\hc" if m == "auroc" else r"\hcl"
                        cells[k, ds, m] = rf"{macro}{mk[k]}{{{vals[k]:.1f}}}{{{vals['prior']:.1f}}}"
        for k, name in DIAG_ROWS:
            lead = r"\ours " if k == "logreg" else r"\base "
            lines.append(lead + name + " & " + " & ".join(cells[k, ds, m] for ds, _ in DATASETS for m in ("auroc", "ece"))
                         + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--tags", nargs="+", default=list(BACKBONES))
    args = ap.parse_args()
    out = ROOT / "results" / "tables"
    out.mkdir(parents=True, exist_ok=True)
    (out / "table_alloc.tex").write_text(table_alloc(args.tags))
    (out / "table_alloc_small.tex").write_text(table_alloc_small(args.tags))
    (out / "table_diag.tex").write_text(table_diag(args.tags))
    print("wrote paper/tables/table_alloc.tex, table_alloc_small.tex, table_diag.tex")


if __name__ == "__main__":
    main()
