"""Table of the execution-layer ablations (e8), generated from results/e8/<tag>/summary.json; never edit the .tex by hand.

One column wide: one block per backbone under a \\grp header row; rows are the
variants that each change one execution design of the typed plan, run without verification (Plan-Only); cells are the change
in EM against the full configuration on the same test questions, tinted by the change itself (\\hct against 0; reference
0 = the full configuration), with * where the paired bootstrap 95% interval (scripts/e8_summarize.py) excludes 0.
Input:  results/e8/<tag>/summary.json
Output: paper/tables/table_e8.tex (a tabular; caption and float live in the section file)
Usage:  python3 scripts/make_table_e8.py [--tags llama31-8b qwen3-8b]      standard library only
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATASETS = [("hotpotqa", "HotpotQA"), ("2wikimultihopqa", "2Wiki"), ("musique", "MuSiQue")]
BACKBONES = {"llama31-8b": "Llama-3.1-8B-Instruct", "qwen3-8b": "Qwen3-8B"}
ROWS = [("no_sink", "last step without the question"), ("short", "answers not copied verbatim"),
        ("k5", "5 passages instead of 8"), ("cmp_llm", "CMP answered by the LM"),
        ("untyped", "retrieve-and-read for every step"), ("no_check", "no plan check")]


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--tags", nargs="+", default=list(BACKBONES))
    args = ap.parse_args()
    ncol = 1 + len(DATASETS)
    lines = ["% Generated by scripts/make_table_e8.py from results/e8/<tag>/summary.json. Do not edit by hand.",
             r"\begin{tabular}{@{}l" + "c" * len(DATASETS) + r"@{\hspace{\tabcolsep}}}", r"\toprule",
             r"Variant ($\Delta$EM vs.\ full) & " + " & ".join(n for _, n in DATASETS) + r" \\", r"\midrule"]
    for t, tag in enumerate(args.tags):
        p = ROOT / "results" / "e8" / tag / "summary.json"
        d = json.loads(p.read_text()) if p.exists() else {}
        if t:
            lines.append(r"\midrule")
        full = " / ".join(f"{d[ds]['full']['em']:.1f}" if ds in d else r"\tbd" for ds, _ in DATASETS)
        lines.append(rf"\grp{{{ncol}}}{{{BACKBONES[tag]} \textmd{{(full: {full})}}}} \\")
        for key, label in ROWS:
            cells = []
            for ds, _ in DATASETS:
                r = d.get(ds, {}).get(key)
                if not r:
                    cells.append(r"\tbd")
                    continue
                sig = r["lo"] > 0 or r["hi"] < 0
                txt = f"{r['d_em']:+.1f}" + (r"$^{*}$" if sig else r"\phantom{$^{*}$}")
                cells.append(rf"\hct{{{r['d_em']:.1f}}}{{0}}{{{txt}}}")
            lines.append(r"\base " + label + " & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    out = ROOT / "results" / "tables" / "table_e8.tex"
    out.write_text("\n".join(lines))
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
