"""Figure 3 of the paper (quality-cost curves) as pgfplots, from the CSVs written by scripts/make_fig_qc.py.

One row of three panels (HotpotQA, 2WikiMultiHopQA, MuSiQue) per backbone that has a CSV; x = tokens per question (log),
y = EM. The method (price sweep), IRCoT (three reduced budgets and the official setting) and the method with plan-level
escalation (e9 price sweep) are lines in the first three validated categorical colours (blue #2a78d6 / orange #eb6834 /
aqua #1baf7a: dataviz validator 2026-10-08, worst adjacent CVD dE 9.2, normal 27.6; aqua is below 3:1 on white, so it has
its own marker, a legend entry and a direct label); Self-Consistency over k is a thin neutral line; the other baselines are
neutral points labelled directly, so identity never rests on colour.
Input:  results/figures/qc_<tag>.csv (dataset, series, tokens, em)
Output: paper/figures/data/qc_<tag>_<ds>_{ours,ircot,sc,points}.csv and paper/figures/fig3_qc.tex
Usage:  python3 scripts/make_fig3.py      standard library only; rerun after make_fig_qc.py
"""
import csv
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATASETS = [("hotpotqa", "HotpotQA"), ("2wikimultihopqa", "2WikiMultiHopQA"), ("musique", "MuSiQue")]
BACKBONES = [("llama31-8b", "Llama-3.1-8B"), ("qwen3-8b", "Qwen3-8B")]
LINES = {"ours": "ours", "ircot": "ircot", "sc": "sc", "esc": "esc"}
SHORT = {"Standard RAG": "RAG", "Adaptive-Cons.": "AC", "Self-Ask": "Self-Ask", "Search-o1": "Search-o1",
         "PyRAG": "PyRAG", "Plan-and-Budget": "P\\&B", "Adaptive-RAG": "A-RAG"}
# label anchors that keep neighbouring labels apart (checked on the rendered PDF)
ANCHOR = {"PyRAG": "north west", "P\\&B": "south east", "AC": "south", "RAG": "north"}
ANCHOR_DS = {("2wikimultihopqa", "Self-Ask"): "south east"}   # 2Wiki: Self-Ask sits just above-left of Search-o1
# per backbone where a label would sit on a curve of the method (checked on the rendered PDF, 2026-10-08)
# (anchor, vertical shift in pt): the label is moved off the curves of the method
ANCHOR_TAG = {("qwen3-8b", "hotpotqa", "Search-o1"): ("north", -9), ("qwen3-8b", "2wikimultihopqa", "Self-Ask"): ("east", 0),
              ("qwen3-8b", "2wikimultihopqa", "Search-o1"): ("north", -8), ("qwen3-8b", "musique", "Self-Ask"): ("east", 0),
              # MuSiQue: Standard RAG is the lowest point, so a label below it hit the x axis (2026-10-08, larger labels)
              ("qwen3-8b", "musique", "Standard RAG"): ("west", 2), ("llama31-8b", "musique", "Standard RAG"): ("west", 1)}


def main():
    data_dir = ROOT / "results" / "figures" / "data"
    data_dir.mkdir(parents=True, exist_ok=True)
    rows = []
    for tag, name in BACKBONES:
        p = ROOT / "results" / "figures" / f"qc_{tag}.csv"
        if not p.exists():
            continue
        series = defaultdict(list)
        for r in csv.DictReader(p.open()):
            series[r["dataset"], r["series"]].append((float(r["tokens"]), float(r["em"])))
        for ds, _ in DATASETS:
            for s in LINES:
                pts = sorted(series.get((ds, s), []))
                with (data_dir / f"qc_{tag}_{ds}_{s}.csv").open("w") as f:
                    f.write("tokens,em\n" + "".join(f"{t:.0f},{e:.2f}\n" for t, e in pts))
            with (data_dir / f"qc_{tag}_{ds}_points.csv").open("w") as f:
                f.write("tokens,em,label,anchor,dy\n")
                for long, short in SHORT.items():
                    for t, e in series.get((ds, long), []):
                        anchor, dy = ANCHOR_TAG.get((tag, ds, long), (ANCHOR_DS.get((ds, long), ANCHOR.get(short, "west")), 0))
                        f.write(f"{t:.0f},{e:.2f},{short},{anchor},{dy}\n")
        rows.append((tag, name))
    if not rows:
        raise SystemExit("no results/figures/qc_<tag>.csv yet; run scripts/make_fig_qc.py first")
    out = [r"% Generated by scripts/make_fig3.py from results/figures/qc_<tag>.csv. Do not edit by hand.",
           r"\definecolor{cOurs}{HTML}{2A78D6}\definecolor{cIRCoT}{HTML}{EB6834}\definecolor{cEsc}{HTML}{1BAF7A}\definecolor{cNeutral}{HTML}{8A8F98}",
           r"\begin{tikzpicture}",
           r"\begin{groupplot}[group style={group size=3 by %d, horizontal sep=1.1cm, vertical sep=1.5cm}," % len(rows),
           r"  cw, width=0.36\linewidth, height=0.27\linewidth, xmode=log, log basis x=10,",
           r"  xlabel={tokens per question},",
           r"  xtick={1000,3000,10000,30000}, xticklabels={1k,3k,10k,30k}, enlarge x limits=0.04,",
           r"  title style={at={(0,1.04)}, anchor=south west}, legend style={legend columns=4, /tikz/every even column/.append style={column sep=8pt}}]"]
    for i, (tag, name) in enumerate(rows):
        for j, (ds, dname) in enumerate(DATASETS):
            f = lambda s: f"figures/data/qc_{tag}_{ds}_{s}.csv"
            opts = [r"ylabel={EM \textcolor{black!60}{(%s)}}" % name] if j == 0 else []
            if i == 0:
                opts.append("title={%s}" % dname)
            if i == 0 and j == 0:
                opts.append("legend to name=qcleg")
            out.append(r"\nextgroupplot[%s]" % ", ".join(opts))
            out.append(r"  \addplot[draw=cNeutral, line width=0.6pt, mark=none] table[col sep=comma, x=tokens, y=em] {%s};" % f("sc"))
            out.append(r"  \addplot[cIRCoT, cwline, mark=square*] table[col sep=comma, x=tokens, y=em] {%s};" % f("ircot"))
            out.append(r"  \addplot[cOurs, cwline, mark=*] table[col sep=comma, x=tokens, y=em] {%s};" % f("ours"))
            if (data_dir / f"qc_{tag}_{ds}_esc.csv").read_text().count("\n") > 1:   # escalation sweep, labelled at its end
                out.append(r"  \addplot[cEsc, cwline, mark=triangle*] table[col sep=comma, x=tokens, y=em] {%s} "
                           r"node[pos=1, anchor=west, font=\scriptsize, text=black!85] {\method{}};" % f("esc"))
            out.append(r"  \addplot[only marks, mark=diamond*, mark size=1.6pt, draw=black!75, fill=white, "
                       r"nodes near coords, point meta=explicit symbolic, visualization depends on={value \thisrow{anchor} \as \lab}, visualization depends on={\thisrow{dy} \as \labdy}, "
                       r"every node near coord/.append style={font=\scriptsize, text=black!85, anchor=\lab, inner sep=1.5pt, yshift=\labdy pt}] "
                       r"table[col sep=comma, x=tokens, y=em, meta=label] {%s};" % f("points"))
            if i == 0 and j == 0:
                out.append(r"  \legend{{Self-Consistency ($k=1\ldots10$)}, {IRCoT (three reduced budgets; official setting at right)}, {\method{} w/o escalation (price sweep)}, {\method{} (budget sweep)}, {other baselines}}")
    out += [r"\end{groupplot}",
            r"\node[anchor=south] at ($(group c2r1.north)+(0,0.55cm)$) {\pgfplotslegendfromname{qcleg}};",
            r"\end{tikzpicture}", ""]
    (ROOT / "results" / "figures" / "fig3_qc.tex").write_text("\n".join(out))
    print(f"wrote paper/figures/fig3_qc.tex ({len(rows)} backbone row(s)) and its data files")


if __name__ == "__main__":
    main()
