"""Table of the repair and damage rates of the verification operators on TXT steps (from results/e3/<tag>/models/<ds>_summary.json).

Why: the text said that the operators
repair few errors with one operator's numbers; the table gives every TXT operator on both backbones. The rates are the
calibration estimates of the quality model (scripts/e3_fit.py): rho+ = P(right after the operator | default wrong),
rho- = P(wrong after | default right), each operator applied to every step of the 500 calibration questions.
Output: paper/tables/table_rho.tex (a tabular; caption and float live in the section file)
Usage:  python3 scripts/make_table_rho.py      standard library only
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TAGS = [("llama31-8b", "Llama-3.1-8B-Instruct"), ("qwen3-8b", "Qwen3-8B")]
DATASETS = [("hotpotqa", "HotpotQA"), ("2wikimultihopqa", "2Wiki"), ("musique", "MuSiQue")]
OPS = [("VOTE3", "VOTE-3"), ("VOTE5", "VOTE-5"), ("REGROUND", "REGROUND"), ("VOTE5+REGROUND", r"VOTE-5$\to$ALT"),
       ("DEEPGROUND", "DEEPGROUND")]


def main():
    ncol = 1 + len(DATASETS)
    lines = ["% Generated by scripts/make_table_rho.py from results/e3/<tag>/models/<ds>_summary.json. Do not edit by hand.",
             r"\begin{tabular}{@{}l" + "c" * len(DATASETS) + "@{}}", r"\toprule",
             r"TXT operator ($\rho^{+}$ / $\rho^{-}$, \%) & " + " & ".join(n for _, n in DATASETS) + r" \\", r"\midrule"]
    for t, (tag, name) in enumerate(TAGS):
        if t:
            lines.append(r"\midrule")
        rho = {ds: json.loads((ROOT / "results" / "e3" / tag / "models" / f"{ds}_summary.json").read_text())["rho"]
               for ds, _ in DATASETS}
        lines.append(rf"\grp{{{ncol}}}{{{name}}} \\")
        for key, label in OPS:
            cells = []
            for ds, _ in DATASETS:
                rp, rm = rho[ds][f"TXT:{key}"]
                cells.append(f"{100 * rp:.1f} / {100 * rm:.1f}")
            lines.append(r"\base " + label + " & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    out = ROOT / "results" / "tables" / "table_rho.tex"
    out.write_text("\n".join(lines))
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
