"""Table of the escalation ablations (e9): where the gain of plan-level escalation comes from. Generated from the e9 results;
never edit the .tex by hand.

Style as the other results tables: one block per backbone under a \\grp header row, the method's row marked
with \\ours, best EM bold and second underlined per block and column, EM cells tinted by their change against this table's
reference, the method with escalation (fine scale \\hcs, key \\tintlegendfine: the rows differ by a few points). Tokens per
question (thousands, prompt + completion, the plan's default execution included for escalated questions) are plain numbers.
Rows, all at the same operating point (E9_MODE and BUDGET below):
  \\method{}               the composed reliability decides (results/e9/<tag>/priced.json, plan/<mode>/<budget>)
  w/o propagation         the reliability without propagation along the plan (noprop/...)
  type prior              the plan's step types alone (prior/...)
  one price for both      verification and escalation priced with a single lambda (plan/joint/<budget>)
  random escalation       as many escalations per alternative as the method, to random questions (mean of 20 draws)
  \\method{} w/o escalation  e3's method at its priced verification budget (refs.ours, own_tok)
  pre-execution router    the same T5-large classifier as Adaptive-RAG, trained to pick {Plan-Only, IRCoT} from the question
                          text before anything runs (results/e9/<tag>/arag/summary.json, pre_plan_ircot)
  Adaptive-RAG            {no retrieval, single-step RAG, IRCoT} from the question text (arag)
  oracle                  escalates by the realised gain under the same spend; an upper bound, grey, no tint or marks
Input:  results/e9/<tag>/<E9_SRC>.json (make_table1.py), results/e9/<tag>/arag/summary.json
Output: paper/tables/table_esc.tex (a tabular; caption and float live in the section file)
Usage:  python3 scripts/make_table_esc.py [--tags llama31-8b qwen3-8b] [--budget B_IRCoT/2] [--mode workload] [--priced ...]
        standard library only
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))
from make_table1 import E9_MODE, E9_SRC  # noqa: E402   one setting for the main table and this one

DATASETS = [("hotpotqa", "HotpotQA"), ("2wikimultihopqa", "2Wiki"), ("musique", "MuSiQue")]
BACKBONES = {"llama31-8b": "Llama-3.1-8B-Instruct", "qwen3-8b": "Qwen3-8B"}
BUDGET = "B_IRCoT/2"   # the operating point of the escalation rows
# The answering-step-only signal is not a row; w/o propagation and
# type prior stay only if the method's signal does not lose to them on average at equal spend (ABLATED below).
ROWS = [("plan", r"\method{}"), ("noprop", r"\quad w/o propagation"),
        ("prior", r"\quad type prior"), ("joint", r"\quad one price for both"), ("random", r"\quad random escalation"),
        ("noesc", r"\method{} w/o escalation"), ("pre", r"Pre-exec.\ router"), ("arag", r"Adaptive-RAG (official)"),
        ("oracle", r"Oracle (upper bound)")]
RULE_BEFORE = {"noesc", "oracle"}
# Set by scripts/e9_signal_check.py on the final maps (2026-10-08 02:40): at equal spend, averaged over both backbones and
# all datasets, the composed reliability reaches 42.55 EM, w/o propagation 42.58 and the type prior 42.58, so by the rule
# fixed beforehand neither row is shown and the text claims nothing about which signal is better.
ABLATED = ()
HEADER = ("% Generated by scripts/make_table_esc.py from results/e9/<tag>/priced.json and results/e9/<tag>/arag/summary.json.\n"
          "% Do not edit by hand.\n")


def load(path):
    return json.loads(path.read_text()) if path.exists() else {}


def cells_of(tag, mode, budget, priced="priced.json"):
    """{(row, ds): (em, tok)}; rows without results are left out."""
    e9 = load(ROOT / "results" / "e9" / tag / priced)
    arag = load(ROOT / "results" / "e9" / tag / "arag" / "summary.json").get("methods", {})
    out = {}
    for ds, _ in DATASETS:
        r = e9.get(ds)
        if r:
            for row in ("plan", "noprop", "sink", "prior", "random", "oracle", "joint"):
                p = r["points"].get(f"plan/joint/{budget}" if row == "joint" else f"{row}/{mode}/{budget}")
                if p:
                    out[row, ds] = (p["em"], p["tok"])
            out["noesc", ds] = (r["refs"]["ours"], r["own_tok"])
        for row, key in (("pre", "pre_plan_ircot"), ("arag", "arag")):
            if ds in arag.get(key, {}):
                out[row, ds] = (arag[key][ds]["em"], arag[key][ds]["tok"])
    return out


def marks(values):
    """{row: '[\\textbf]' | '[\\underline]' | ''} for best / second best (rounded to one decimal, ties share the mark)."""
    vals = sorted({round(v, 1) for v in values.values()}, reverse=True)
    return {r: r"[\textbf]" if round(v, 1) == vals[0] else (r"[\underline]" if len(vals) > 1 and round(v, 1) == vals[1] else "")
            for r, v in values.items()}


def render(tags, mode, budget, priced="priced.json"):
    ncol = 1 + 2 * len(DATASETS)
    lines = [HEADER + r"\begin{tabular}{@{}l" + "cc" * len(DATASETS) + "@{}}", r"\toprule",
             " & " + " & ".join(rf"\multicolumn{{2}}{{c}}{{{name}}}" for _, name in DATASETS) + r" \\",
             "".join(rf"\cmidrule(lr){{{2 + 2 * i}-{3 + 2 * i}}}" for i in range(len(DATASETS))),
             r"Variant & " + " & ".join(r"EM & Tok" for _ in DATASETS) + r" \\", r"\midrule"]
    for t, tag in enumerate(tags):
        if t:
            lines.append(r"\midrule")
        lines.append(rf"\grp{{{ncol}}}{{{BACKBONES[tag]}}} \\")
        c = cells_of(tag, mode, budget, priced)
        shown = [r for r, _ in ROWS if r not in ("noprop", "prior") or r in ABLATED]
        mk = {ds: marks({row: c[row, ds][0] for row in shown if (row, ds) in c and row != "oracle"}) for ds, _ in DATASETS}
        for row, name in [(r, n) for r, n in ROWS if r not in ("noprop", "prior") or r in ABLATED]:
            if row in RULE_BEFORE:
                lines.append(r"\cmidrule(lr){1-" + str(ncol) + "}")
            cells = []
            for ds, _ in DATASETS:
                if (row, ds) not in c:
                    cells += [r"\tbd", r"\tbd"]
                    continue
                em, tok = c[row, ds]
                ref = c.get(("plan", ds))
                if row == "oracle":
                    cells.append(rf"\textcolor{{black!55}}{{{em:.1f}}}")
                elif ref is None:
                    cells.append(f"{em:.1f}")
                else:
                    cells.append(rf"\hcs{mk[ds].get(row, '')}{{{em:.1f}}}{{{ref[0]:.1f}}}")   # fine tint scale (+-5)
                cells.append(rf"\textcolor{{black!55}}{{{tok / 1000:.1f}}}" if row == "oracle" else f"{tok / 1000:.1f}")
            label = rf"\textcolor{{black!55}}{{{name}}}" if row == "oracle" else name
            lines.append((r"\ours " if row == "plan" else r"\base ") + label + " & " + " & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--tags", nargs="+", default=list(BACKBONES))
    ap.add_argument("--mode", default=E9_MODE, choices=["cal", "workload"])
    ap.add_argument("--budget", default=BUDGET, help="B_IRCoT/2, B_SO1 or E<extra tokens>, as in priced.json")
    ap.add_argument("--priced", default=f"{E9_SRC}.json", help="e.g. priced.json (500 devcal questions) or priced_traincal.json")
    args = ap.parse_args()
    path = ROOT / "results" / "tables" / "table_esc.tex"
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render(args.tags, args.mode, args.budget, args.priced))
    print(f"wrote {path} ({args.mode}, {args.budget})")


if __name__ == "__main__":
    main()
